name: Publish notebook as GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert nbformat

      - name: Convert notebook → HTML in /docs as index.html
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          jupyter nbconvert --to html "notebooks/Geospatial Data Analysis.ipynb" \
            --output-dir docs --output index
          # Append a Back-to-Repo link to the bottom
          cat >> docs/index.html <<'EOF'
          <hr>
          <p style="text-align:center;margin-top:16px">
            <a href="https://github.com/bing-er/Geospatial-Data-Analysis-with-Python"
               style="font-size:16px;text-decoration:none;">⬅ Back to Repository</a>
          </p>
          EOF
          ls -lah docs

      - name: Commit generated site files
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add docs/index.html docs/.nojekyll
          git commit -m "Auto-publish notebook to GitHub Pages (index.html)" || echo "No changes"
          git push
