name: Publish notebook as GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install jupyter nbconvert nbformat

      - name: Convert notebook → HTML into /docs as index.html
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          jupyter nbconvert --to html "notebooks/Geospatial Data Analysis.ipynb" \
            --output-dir docs --output index
          ls -lah docs

      - name: Commit generated site files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/index.html docs/.nojekyll
          git commit -m "Auto-publish notebook to GitHub Pages (index.html)" || echo "No changes"
          git push
